# **Class 20: 23rd July 2022: MongoDB Contd..**

**SQL:** Structured Query Language: Creating Schema before inserting data. We scale vertically.

**NoSQL:** Not only SQL: No need to create schema before creating table: Document based data (json based dataset/dictionary format) can be stored in MongoDB. Not supposed to create complex data modelling here unlike SQL database. We can try scale horizontally.
Cassandra, Neo4j, Elastic, Hbase are other examples of NoSQL Databases apart from MongoDB. Indexing and Searching becomes easy. We always ty to think about complexity, use-case etc while selecting different database.

**Django** is a python framework that connect frontend and backend. It is not a database.

**MongoDB Atlas:** Cloud Hosted MongoDB service provided by AWS, Azure, Google: Flexibility present to choose different storage options and features according to our requirements. M10 or higher version will be able to connect with BI Tool such as PowerBI

**MongoDB Compass:** Offline Version of MongoDB Service

Creating Collection/Document inside Database in NoSQL system is same as creating table inside Databse in SQL system. For every document, MongoDB will give object ID which will help us in index/search operation. We can even give our own ID of each document.

In [ ]:
pip install pymongo  #Write in Command Prompt Terminal of Pycharm
pip install "pymongo[srv]" #Write in Command Prompt Terminal of Pycharm

In [ ]:
#test.py file 
#MongoDB Access in Python
import pymongo
client = pymongo.MongoClient("mongodb+srv://gauravratan:ratan94@cluster0.hunum.mongodb.net/?retryWrites=true&w=majority") #Connectivity between python and MongoDB
db = client.test 

#Dictionary
data = {
    "name" : "Anshu",
    "mail_id" : "anshu@gmail.com",
    "subject" : ["Data Science","Big Data","Data Analytics"]
}

list_of_records = [
    {'companyName': 'iNeuron',
     'product': 'Affordable AI',
     'courseOffered': 'Machine Learning with Deployment'},

    {'companyName': 'iNeuron',
     'product': 'Affordable AI',
     'courseOffered': 'Deep Learning for NLP and Computer vision'},

    {'companyName': 'iNeuron',
     'product': 'Master Program',
     'courseOffered': 'Data Science Masters Program'}
]

#JSON Data
data1 = {"packetType":"D","data":{"checkEngineLightFlag":"F","batteryVoltageStableTime":0,"batteryVoltageStable":"0","batteryVoltageOff":"12.42","batteryCrankParamTN":"-0.08","batteryCrankParamVN":"0.00","batteryCrankParamTP":"-0.08","batteryCrankParamVP":"0.00","batteryCrankParamTT":"-0.00008","batteryCrankParamV0":"0.00","batteryVoltageMaxOn":"13.05","batteryVoltageMinOn":"12.97","batteryVoltageMaxOff":"12.46","batteryVoltageMinOff":"12.36","batteryVoltageOnAverage":"13.02","engineLoadMax":"84","engineLoadAverage":"39.98","rpmMax":"3487","rpmAverage":"1431.29","gpsSpeedAverage":"21.99","vssMax":"53.44","vssAverage":"23.06","tcuTemperatureMin":"82.40","tcuTemperatureMax":"109.40","tcuTemperatureAverage":"104.87","coolantMin":"158.00","coolantMax":"188.60","coolantAverage":"180.20","packetStartLocal":1508143346000,"tripStartLocal":1508143346000,"milIndicator":"F","monitorsNotReady":0,"imei":"60DF5417","gatewayTs":1515613306592,"diagnosticTroubleCodeData":[345345],"diagnosticPidData":[[64768,47,100],[64768,1,517376],[64800,1,262144],[64768,5,125]]},"header":{"iwrapVer":"1.9.20","sourceSystem":"CDP","configVer":"1.1","oemName":"HUM","unitType":0,"cpVer":"7.50.1.9","igpsVer":"1.3.7","messageType":"Notification","pomVer":"1.0","headerVer":"V6","timestamp":0,"deviceType":"InDrive","visorVer":"1.4.35","transactionId":"53098471-7787-4160-94b3-cd69dcc70416","deviceSerialNo":"60DF5417","subOrganization":"HUM","organization":"HUM","imei":"60DF5417","operation":"Notification"}}

#Creating Database
database = client['MyInfo']

#Creating Collection/Document inside Database (Same as creating Tables inside Database in SQL Systems)
collection = database["anshu"]

#Storing one or multiple records/documents in collection/document
#In same Collection, we are able to save different type of data. This means we are not defining Schema initially. 
collection.insert_one(data)
collection.insert_many(list_of_records)
collection.insert_one(data1)

#Returning all records present in collection
records = collection.find()
for i in records:
    print(i)

#Extracting where we have 'companyName' = 'iNeuron'
iNeuron = collection.find({"companyName" : "iNeuron"})
for i in iNeuron:
    print(i)

#Those data where course offered is greater then "E"
data2 = collection.find({"courseOffered" : {"$gt" : "E"}})
for i in data2:
    print(i)

JSON Viewer: http://jsonviewer.stack.hu/
We can convert json data into dictionary and then insert into MongoDB.
Values of Dictionary should not be null to insert into the database

In [ ]:
#test3.py
import pymongo
client = pymongo.MongoClient("mongodb+srv://gauravratan:ratan94@cluster0.hunum.mongodb.net/?retryWrites=true&w=majority") #Connectivity between python and MongoDB
db = client.test

data =  [
        {
            "item": "canvas",
            "qty": 100,
            "size": {"h": 28, "w": 35.5, "uom": "cm"},
            "status": "A",
        },
        {
            "item": "journal",
            "qty": 25,
            "size": {"h": 14, "w": 21, "uom": "cm"},
            "status": "A",
        },
        {
            "item": "mat",
            "qty": 85,
            "size": {"h": 27.9, "w": 35.5, "uom": "cm"},
            "status": "A",
        },
        {
            "item": "mousepad",
            "qty": 25,
            "size": {"h": 19, "w": 22.85, "uom": "cm"},
            "status": "P",
        },
        {
            "item": "notebook",
            "qty": 50,
            "size": {"h": 8.5, "w": 11, "uom": "in"},
            "status": "P",
        },
        {
            "item": "paper",
            "qty": 100,
            "size": {"h": 8.5, "w": 11, "uom": "in"},
            "status": "D",
        },
        {
            "item": "planner",
            "qty": 75,
            "size": {"h": 22.85, "w": 30, "uom": "cm"},
            "status": "D",
        },
        {
            "item": "postcard",
            "qty": 45,
            "size": {"h": 10, "w": 15.25, "uom": "cm"},
            "status": "A",
        },
        {
            "item": "sketchbook",
            "qty": 80,
            "size": {"h": 14, "w": 21, "uom": "cm"},
            "status": "A",
        },
        {
            "item": "sketch pad",
            "qty": 95,
            "size": {"h": 22.85, "w": 30.5, "uom": "cm"},
            "status": "A",
        },
    ]


#Creating Database
database = client['Inventory']

#Creating Collection/Document inside Database (Same as creating Tables inside Database in SQL Systems)
collection = database["Table"]

#Storing one or multiple records/documents in collection/document
collection.insert_many(data)

#Fetching all Data
d1= collection.find()
for i in d1:
    print(i)

#Extract where status = 'A'
d2 = collection.find({'status' : 'A'})
for i in d2:
    print(i)

#Extract where status = 'A' or status = 'D'
d3 = collection.find({'status' : {'$in':['A','P']}})
for i in d3:
    print(i)

#Extract where status > 'C'
d4 = collection.find({'status' : {'$gt':'C'}})
for i in d4:
    print(i)

#Extract where quantity >= 100
d5 = collection.find({'qty' : {'$gte': 100}})
for i in d5:
    print(i)

#Extract where qty = 95 and item = 'sketch pad'
d6 = collection.find({'item' : 'sketch pad','qty' : 95})
for i in d6:
    print(i)

#Extract where qty >= 75 and item = 'sketch pad'
d7 = collection.find({'item' : 'sketch pad','qty' : {'$gte' : 75}})
for i in d7:
    print(i)

#Extract where qty >= 75 or item = 'sketch pad'
d8 = collection.find({'$or' : [{'item' : 'sketch pad'},{'qty' : {"$gte" : 75}}]})
for i in d8:
    print(i)

#'Canvas' will be updated to 'Gaurav'
collection.update_one({'item' : 'canvas'},{'$set':{'item' : 'Gaurav'}}) #Will update for one record 
d9 = collection.find({'item' : 'Gaurav'})
for i in d9:
    print(i)

#Delete where item = 'Gaurav'
collection.delete_one({'item' : 'Gaurav'}) #Will delete for one record of item = 'Gaurav'
d10 = collection.find({'item' : 'Gaurav'})
for i in d10:
    print(i)

We can do all these filter/insert/update/delete operations in MongoDB Atlas itself. Same Code needs to be written